
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: D:/vs2022/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      2
      鐢ㄤ簬 x64 鐨?Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣?19.44.35213 鐗?
      鐗堟潈鎵€鏈?C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.44.35213.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      LINK : fatal error LNK1104: 鏃犳硶鎵撳紑鏂囦欢鈥淟IBCMT.lib鈥?
      
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/vs2022/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/cl.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      鐢ㄤ簬 x64 鐨?Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣?19.44.35213 鐗?
      鐗堟潈鎵€鏈?C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
      
      CMakeCCompilerId.c
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/lenovo/Desktop/bishe/myProj/OpenGLDP/build-verify2/CMakeFiles/3.30.4/CompilerIdC/CMakeCCompilerId.obj
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1243 (message)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        娉ㄦ剰: 鍖呭惈鏂囦欢:  C:\\Users\\lenovo\\Desktop\\bishe\\myProj\\OpenGLDP\\build-verify2\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "娉ㄦ剰: 鍖呭惈鏂囦欢:  "
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: D:/vs2022/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      2
      鐢ㄤ簬 x64 鐨?Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣?19.44.35213 鐗?
      鐗堟潈鎵€鏈?C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.44.35213.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      LINK : fatal error LNK1104: 鏃犳硶鎵撳紑鏂囦欢鈥淟IBCMT.lib鈥?
      
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/vs2022/VC/Tools/MSVC/14.44.35207/bin/HostX64/x64/cl.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      鐢ㄤ簬 x64 鐨?Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣?19.44.35213 鐗?
      鐗堟潈鎵€鏈?C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿€?
      
      CMakeCXXCompilerId.cpp
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/lenovo/Desktop/bishe/myProj/OpenGLDP/build-verify2/CMakeFiles/3.30.4/CompilerIdCXX/CMakeCXXCompilerId.obj
      
  -
    kind: "message-v1"
    backtrace:
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:1243 (message)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "E:/cmake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        娉ㄦ剰: 鍖呭惈鏂囦欢:  C:\\Users\\lenovo\\Desktop\\bishe\\myProj\\OpenGLDP\\build-verify2\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "娉ㄦ剰: 鍖呭惈鏂囦欢:  "
